### ISSUE TITLE
Exposed whatweb api key in the code + few suggestions. 

### ISSUE THREAD

**Issue by Ice3man543** [devanshbatham/Gorecon#1]
I think maybe it's intentional, but you've exposed your whatweb api key in the code. That's generally a very bad practice and should be discouraged. Instead, you should allow people to use their own api key which should prevent abuse of the api.

Also, it will be a good idea to run gofmt over your code as that is the standard for go code. Another thing, you should split the code across many files since having a file that big with code is considered a bad programming practice in general and makes it complicated to debug and remove errors etc.

Kudos for open sourcing it, it's a nice idea. Keep up the good work

**Comment by devanshbatham** [comment]
Hey @Ice3man543 thanks for your time , 

Thanks for pointing out the api key leak, I will remove that from the source (after my exams), and instead will ask users to use their own api keys , This tool is just a part of my upcoming project , thats why I made a single .go file(its a horrible practise) , instead of splitting the source between many files , (main reason of releasing this tool ,is just taking suggestions and improvements , I am glad you did that 👍 ) ,

Will consider your suggestions in next stable release of this tool for sure, 👍 
Thanks again mate 👍
